### PR TITLE
Fix hex2str

### PR DESCRIPTION
**Pull request by chcmedeiros**
:link: [zboto Link](https://app.clickup.com/t/86773zb3m)

### CODE REVIEW

**Comment by ftheirs** [comment]
Everything looks good to me :D Can you add some tests for hex functions here:
https://github.com/Zondax/ledger-zxlib/blob/main/tests/hexutils.cpp
With some examples, you can check that **array_to_hexstr** and **hexstr_to_array** are working well!

**Comment by chcmedeiros** [comment]
@ftheirs  sure!

**Comment by chcmedeiros** [comment]
Added tests on zxformat.cpp because it is the file where those functions are defined

**Review by ftheirs — APPROVED** [review]
🚀

**Pull request merged**
