### PR TITLE
Remove unused params on nanoS

### PR DESCRIPTION
**Pull request by 0xPxt**

### CODE REVIEW

**Comment by emmanuelm41** [comment]
@0xPxt do we know why they are there in the first place? Aren't we breaking any other app by changing this?

**Comment by 0xPxt** [comment]
> @0xPxt do we know why they are there in the first place? Aren't we breaking any other app by changing this?

Now that you say this, since the functions are static and there are no calls to them inside view_s.c I guess we can remove them entirely.

**Comment by emmanuelm41** [comment]
But as they are static, how do we know if those functions are not used on any app? At least we should ask the team if they know more about it.

**Comment by emmanuelm41** [comment]
I did not remember that! Nice catch. If we are 100% sure about it, then let's remove them

**Review by emmanuelm41 — APPROVED** [review]

**Pull request merged**
